[project]
name = "jax-ml-template"
version = "0.1.0"
description = "A JAX-based ML project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # Our bread and butter.
    "jax[cuda12]>=0.6.2",
    # Shape checking annotations.
    "jaxtyping>=0.3.2",
    # Swiss army knife of JAX utils.
    "equinox>=0.12.2",
    # Runtime type checking backend (used by jaxtyping).
    "beartype>=0.21.0",
    # Interactive matplotlib widgets in Jupyter.
    "ipympl>=0.9.7",
    # Git-friendly notebook storage.
    "jupytext>=1.17.2",
]

[tool.ruff]
# Ignore F821 and F722 for jaxtyping string annotations
lint.ignore = ["F821", "F722"]
